<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * AdminUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminUserRepository extends EntityRepository implements UserRepositoryInterface
{
    public function findOneByEmail($email)
    {
        return $this->createQueryBuilder('o')
            ->andWhere('o.emailCanonical = :email')
            ->setParameter('email', $email)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * {@inheritdoc}
     */
    public function findOneByConfirmationToken($token)
    {
        return $this->createQueryBuilder('o')
            ->andWhere('o.confirmationToken = :token')->setParameter('token', $token)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
