<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * ShopUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopUserRepository extends EntityRepository implements UserRepositoryInterface
{
    public function findOneByEmail($email)
    {
        return $this->createQueryBuilder('o')
            ->innerJoin('o.customer', 'customer')
            ->andWhere('customer.emailCanonical = :email')
            ->setParameter('email', $email)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
