admin:
    resource: '@AdminBundle/Controller'
    type: annotation
    prefix: /admin

admin_user:
    resource: '@AdminBundle/Resources/config/routing_user.yml'
    prefix: /admin

shop:
    resource: '@ShopBundle/Controller'
    type: annotation

shop_account:
    resource: '@ShopBundle/Controller/Account'
    prefix: /account

shop_user:
    resource: "@ShopBundle/Resources/config/routing_user.yml"
