# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

    app.canonicalizer:
        class: AppBundle\Util\Canonicalizer

    app.canonicalizer.subscriber:
        class: AppBundle\EventListener\CanonicalizerSubscriber
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    app.util.flash_bag:
        class: AppBundle\Util\FlashBag
        autowire: true

    app.util.pagination:
        class: AppBundle\Util\Pagination
        autowire: true