# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

    app.shop_user_repository:
        class:  Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\ShopUser

    app.admin_user_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\AdminUser

    app.canonicalizer:
        class: AppBundle\Util\Canonicalizer

    app.admin_user_provider.email_or_name_based:
        class: AppBundle\Provider\UsernameOrEmailProvider
        arguments:
            - 'AppBundle\Entity\AdminUser'
            - '@app.admin_user_repository'
            - '@app.canonicalizer'

    app.shop_user_provider.email_or_name_based:
        class: AppBundle\Provider\UsernameOrEmailProvider
        arguments:
            - 'AppBundle\Entity\ShopUser'
            - '@app.shop_user_repository'
            - '@app.canonicalizer'

    app.controller.security:
        class: AppBundle\Controller\SecurityController
        arguments: ['@security.authentication_utils', '@form.factory', '@templating']

    app.controller.user:
        class: AppBundle\Controller\UserController
        arguments: ['@form.factory', '@templating']

    app.canonicalizer.subscriber:
        class: AppBundle\EventListener\CanonicalizerSubscriber
        arguments: ['@app.canonicalizer']
        tags:
            - { name: doctrine.event_subscriber }

    app.user_encode_password.subscriber:
        class: AppBundle\EventListener\EncodePasswordSubscriber
        arguments: [ "@security.password_encoder" ]
        tags:
            - { name: doctrine.event_subscriber }

    app.last_login_subscriber:
        class: AppBundle\EventListener\LastLoginSubscriber
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: kernel.event_subscriber }