# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

    app.shop_user_repository:
        class:  Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\ShopUser

    app.admin_user_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\AdminUser

    app.canonicalizer:
        class: AppBundle\Util\Canonicalizer

    app.admin_user_provider.email_or_name_based:
        class: AppBundle\Provider\UsernameOrEmailProvider
        arguments:
            - 'AppBundle\Entity\AdminUser'
            - '@app.admin_user_repository'
            - '@app.canonicalizer'

    app.shop_user_provider.email_or_name_based:
        class: AppBundle\Provider\UsernameOrEmailProvider
        arguments:
            - 'AppBundle\Entity\ShopUser'
            - '@app.shop_user_repository'
            - '@app.canonicalizer'

    app.controller.security:
        class: AppBundle\Controller\SecurityController
        autowire: true
        #arguments: ['@security.authentication_utils', '@form.factory', '@templating']

    app.controller.shop_user:
        class: AppBundle\Controller\UserController
        autowire: true
        arguments:
            - '@form.factory'
            - '@templating'
            - '@app.shop_user_repository'
            - '@app.util.token_generator'
            - '@event_dispatcher'
            - '@doctrine.orm.entity_manager'
            - '@translator.default'
            - '%token_ttl%'
            - '@router.default'
            - '@app.util.flash_bag'
            - '@security.token_storage'

    app.canonicalizer.subscriber:
        class: AppBundle\EventListener\CanonicalizerSubscriber
        autowire: true
        #arguments: ['@app.canonicalizer']
        tags:
            - { name: doctrine.event_subscriber }

    app.user_encode_password.subscriber:
        class: AppBundle\EventListener\EncodePasswordSubscriber
        autowire: true
        #arguments: [ "@security.password_encoder" ]
        tags:
            - { name: doctrine.event_subscriber }

    app.last_login_subscriber:
        class: AppBundle\EventListener\LastLoginSubscriber
        autowire: true
        #arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: kernel.event_subscriber }

    app.util.token_generator:
        class: AppBundle\Util\TokenGenerator
        autowire: true

    app.util.flash_bag:
        class: AppBundle\Util\FlashBag
        autowire: true

    app.mailer.user:
        class: AppBundle\Mailer\UserMailer
        autowire: true
        #arguments:
        #    - "@swiftmailer.mailer"
        #    - "@router"
        #    - "@twig"

    app.resetting_request_subscriber:
        class: AppBundle\EventListener\ResettingRequestSubscriber
        autowire: true
        #arguments: ['@app.mailer.user', '@app.helper.flash_bag']
        tags:
            - { name: kernel.event_subscriber }

    app.resetting_reset_subscriber:
        class: AppBundle\EventListener\ResettingResetSubscriber
        autowire: true
        tags:
            - { name: kernel.event_subscriber }